#!/bin/sh
set -e

# Automatically added by dh_python3:
if which pycompile >/dev/null 2>&1; then
    pycompile -p linkmanager
fi

bashrc='/etc/bash.bashrc'
zshrc='/etc/zsh/zshrc'
bash_cmd='eval "$(register-python-argcomplete linkm)"'
zsh_cmd="source linkmanager.zsh"

if [ -f $bashrc ]; then
    LINE_EXIST=$(cat $bashrc | grep -c "$bash_cmd")
    if [ $LINE_EXIST = 0 ]; then
        echo "\n$bash_cmd" >> $bashrc;
    fi
fi
if [ -f $zshrc ]; then
    LINE_EXIST=$(cat $zshrc | grep -c "$zsh_cmd")
    if [ $LINE_EXIST = 0 ]; then
        echo "\n$zsh_cmd" >> $zshrc;
    fi
fi
